// output/HeaderComponent.jsx
import React from 'react';

const HeaderComponent = () => {

  return (
    <header className="header-main">
      <nav className="nav-container">
        <a href="/" className="logo"></a>
        <ul className="nav-menu">
          <li>
            <a href="/" className="nav-link"></a>
          </li>
          <li>
            <a href="/about" className="nav-link"></a>
          </li>
          <li>
            <a href="/services" className="nav-link"></a>
          </li>
          <li>
            <a href="/contact" className="nav-link"></a>
          </li>
        </ul>
      </nav>
    </header>
  );
};

export default HeaderComponent;

// output/HeaderComponent.vue
<template>
  <header :class="'header-main'">
    <nav :class="'nav-container'">
      <a href="/" :class="'logo'" />
      <ul :class="'nav-menu'">
        <li>
          <a href="/" :class="'nav-link'" />
        </li>
        <li>
          <a href="/about" :class="'nav-link'" />
        </li>
        <li>
          <a href="/services" :class="'nav-link'" />
        </li>
        <li>
          <a href="/contact" :class="'nav-link'" />
        </li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  name: 'HeaderComponent',
  data() {
    return {
      // Component data
    };
  },
};
</script>

<style scoped>

</style>
